/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SMMV.Component;

import SMMV.Event.EventMenu;
import SMMV.swing.ButtonMenu;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.raven.swing.scrollbar.ScrollBarCustom;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author user
 */
public class Side_1 extends javax.swing.JPanel {
    private EventMenu event;
    /**
     * Creates new form Side_1
     */
    public Side_1() {
        initComponents();
                setOpaque(false);
              ScrollBarCustom sc = new ScrollBarCustom();
        sc.setForeground(new Color(130,130,130,130));
        jScrollPane1.setVerticalScrollBar(sc);
                jPanel1.setLayout(new MigLayout("wrap, fillx, inset 3", "[fill]", "[]0[]"));
    }
    
       public void initMenu(EventMenu event) {
        this.event = event;
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/1.png")), "Dashboard", 0);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/admin.png")), "Employee Registation", 1); 
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/teacher.png")), "Manage Teacher", 2);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/student.png")), "Manage Student", 3);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/subject.png")), "Manage Subject & Class", 4);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/subject.png")), "Manage Sport & Grade", 5);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/subject.png")), "Subject & Section For Teacher", 6);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/subject.png")), "Student for sport", 7);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/subject.png")), "Sport time table", 8);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/subject.png")), "Manage Teacher Time Table", 9);
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/subject.png")), "Manage Class Time Table", 10);
        addEmpty();
        addMenu(new ImageIcon(getClass().getResource("/SMMV/OL/img/logout.png")), "Logout", 14);
    }

    private void addEmpty() {
        jPanel1.add(new JLabel(), "push");
    }

    private void addMenu(Icon icon, String text, int index) {
        ButtonMenu menu = new ButtonMenu();
        menu.setIcon(icon);
        menu.setText("  " + text);
        jPanel1.add(menu);
        menu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.selected(index);
                setSelected(menu);
            }
        });
    }

    private void setSelected(ButtonMenu menu) {
        for (Component com : jPanel1.getComponents()) {
            if (com instanceof ButtonMenu) {
                ButtonMenu b = (ButtonMenu) com;
                b.setSelected(false);
            }
        }
        menu.setSelected(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new SMMV.Component.Background();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SMMV.Component.Background background1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
