/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SMMV.OL.form;

import SMMV.Connection.connection_ol;
import SMMV.OL.model.User_id_Genarator;
import SMMV.Validation.Validation;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import static org.apache.commons.beanutils.WrapDynaClass.clear;

/**
 *
 * @author user
 */
public class Employee extends javax.swing.JPanel {

    HashMap<String, String> user_type_map = new HashMap<>();
    String EID = "";
    String status = "";

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        setOpaque(false);
        inti();
    }

    private void inti() {
        fname_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Username");
        email_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Email Address");
        mobile_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Mobile");
        password_filed.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Password");
        search_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Search Employee");
        JTableHeader tableHeader = employee_table.getTableHeader();
        tableHeader.setBackground(new Color(0, 0, 255));
        tableHeader.setForeground(Color.WHITE);
        loadUserType();
        loadEmployeeTable();
    }

    private void clear() {
        fname_field.setText("");
        lname_field.setText("");
        email_field.setText("");
        password_filed.setText("");
        mobile_field.setText("");
        user_type_combo.setSelectedIndex(0);
        male.setSelected(false);
        female.setSelected(false);
        buttonGradient1.setEnabled(true);
        email_field.setEditable(true);
        mobile_field.setEditable(true);
    }

    private void loadUserType() {
        try {
            Vector user_typeVector = new Vector();
            user_typeVector.add("Select User Type");

            ResultSet user_typeResult = connection_ol.search("SELECT * FROM `user_type`");

            while (user_typeResult.next()) {

                user_typeVector.add(user_typeResult.getString("type"));
                user_type_map.put(user_typeResult.getString("type"), user_typeResult.getString("user_type_id"));
            }

            user_type_combo.setModel(new DefaultComboBoxModel<>(user_typeVector));
        } catch (java.sql.SQLException e) {
//                        SignIn.logger.warning(e.getMessage());
            System.out.println(e);
        }

    }

    private void loadEmployeeTable() {
        
        try {

            ResultSet rs = connection_ol.search("SELECT * FROM `admin` INNER JOIN `status` ON `admin`.`status_status_id` = `status`.`status_id` "
                    + "INNER JOIN `gender` ON `admin`.`gender_gender_id` = `gender`.`gender_id` "
                    + "INNER JOIN `user_type` ON `admin`.`user_type_user_type_id` = `user_type`.`user_type_id`");

            DefaultTableModel model = (DefaultTableModel) employee_table.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector employeeVector = new Vector();
                employeeVector.add(rs.getString("admin_id"));
                employeeVector.add(rs.getString("fast_name"));
                employeeVector.add(rs.getString("last_name"));
                employeeVector.add(rs.getString("email"));
                employeeVector.add(rs.getString("password"));
                employeeVector.add(rs.getString("mobile"));
                employeeVector.add(rs.getString("user_type.type"));
                employeeVector.add(rs.getString("gender.name"));
                employeeVector.add(rs.getString("status.status"));

                model.addRow(employeeVector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        background1 = new SMMV.Component.Background();
        background2 = new SMMV.Component.Background();
        background4 = new SMMV.Component.Background();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        mobile_field = new javax.swing.JTextField();
        password_filed = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        user_type_combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        buttonGradient1 = new SMMV.Component.ButtonGradient();
        buttonGradient2 = new SMMV.Component.ButtonGradient();
        buttonGradient3 = new SMMV.Component.ButtonGradient();
        lname_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        background3 = new SMMV.Component.Background();
        background5 = new SMMV.Component.Background();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        search_field = new SMMV.Component.Rount_textfieald();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_table = new javax.swing.JTable();

        background1.setBackground(new java.awt.Color(0, 0, 0));

        background4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SMMV/OL/img/admin.png"))); // NOI18N

        javax.swing.GroupLayout background4Layout = new javax.swing.GroupLayout(background4);
        background4.setLayout(background4Layout);
        background4Layout.setHorizontalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background4Layout.setVerticalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Manage Employee");

        fname_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        email_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        mobile_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        password_filed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User Type");

        user_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        male.setText("Male");

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        female.setText("Female");

        buttonGradient1.setText("Add New Employee");
        buttonGradient1.setColor1(new java.awt.Color(0, 0, 153));
        buttonGradient1.setColor2(new java.awt.Color(139, 139, 252));
        buttonGradient1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1ActionPerformed(evt);
            }
        });

        buttonGradient2.setText("Update");
        buttonGradient2.setColor1(new java.awt.Color(0, 0, 153));
        buttonGradient2.setColor2(new java.awt.Color(139, 139, 252));
        buttonGradient2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGradient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient2ActionPerformed(evt);
            }
        });

        buttonGradient3.setText("Deactive");
        buttonGradient3.setColor1(new java.awt.Color(0, 0, 153));
        buttonGradient3.setColor2(new java.awt.Color(139, 139, 252));
        buttonGradient3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGradient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient3ActionPerformed(evt);
            }
        });

        lname_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Last Name");

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(background2Layout.createSequentialGroup()
                        .addComponent(buttonGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGradient3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(background2Layout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(43, 43, 43)
                        .addComponent(female))
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(mobile_field)
                    .addComponent(email_field)
                    .addGroup(background2Layout.createSequentialGroup()
                        .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(password_filed)
                    .addComponent(user_type_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                        .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background2Layout.createSequentialGroup()
                                .addComponent(fname_field)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(background2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(81, 81, 81)))
                        .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(mobile_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(password_filed, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(user_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        background5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SMMV/OL/img/search.png"))); // NOI18N

        javax.swing.GroupLayout background5Layout = new javax.swing.GroupLayout(background5);
        background5.setLayout(background5Layout);
        background5Layout.setHorizontalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background5Layout.setVerticalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Search Employee");

        search_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_fieldKeyPressed(evt);
            }
        });

        employee_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        employee_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Password", "Mobile", "User Type", "Gender", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employee_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employee_table);

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addComponent(search_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background3Layout.createSequentialGroup()
                        .addComponent(background5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(background5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(background2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(background3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1ActionPerformed

        String user_type = String.valueOf(user_type_combo.getSelectedItem());
        if (fname_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Fast Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (lname_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (email_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Email Address", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!email_field.getText().matches(Validation.EMAIL_VALIDATION.validate())) {
            JOptionPane.showMessageDialog(this, "Your Email Address Is Invalide", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (mobile_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Mobile Number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!mobile_field.getText().matches(Validation.MOBILE_NUMBER_VALIDATION.validate())) {
            JOptionPane.showMessageDialog(this, "Your Mobile Number Is Invalide", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!male.isSelected() && !female.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please Select Your Gender", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            int genser = 0;

            if (male.isSelected()) {
                genser = 1;
            }
            if (female.isSelected()) {
                genser = 2;
            }

            try {
                
                ResultSet rs = connection_ol.search("SELECT * FROM `admin` WHERE `email`='"+email_field.getText()+"' OR `mobile`='"+mobile_field.getText()+"'");
                
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Email or Mobile Already Use!", "Warning", JOptionPane.WARNING_MESSAGE);
                    clear();
                }else{
                    connection_ol.iud("INSERT INTO `admin` (`admin_id`,`fast_name`,`last_name`,`email`,`password`,`mobile`,`user_type_user_type_id`,`status_status_id`,`gender_gender_id`) "
                        + "VALUES ('" + User_id_Genarator.User_id_Genarator() + "','" + fname_field.getText() + "','" + lname_field.getText() + "','" + email_field.getText() + "','" + password_filed.getPassword() + "',"
                        + "'" + mobile_field.getText() + "','" + user_type_map.get(user_type) + "','1','" + genser + "')");

                System.out.println("Success");
                loadEmployeeTable();
                clear();
                }

                

            } catch (Exception e) {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_buttonGradient1ActionPerformed

    private void buttonGradient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient2ActionPerformed

        if (employee_table.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please Select Employee to update or remove", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String fname = fname_field.getText();
            String lname = lname_field.getText();
            String password = String.valueOf(password_filed.getPassword());
            String user_type = String.valueOf(user_type_combo.getSelectedItem());

            if (fname.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Your Fast Name", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (lname.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Your Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Your Password", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (user_type.equals("Select User Type")) {
                JOptionPane.showMessageDialog(this, "Please Enter Your Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (!male.isSelected() && !female.isSelected()) {
                JOptionPane.showMessageDialog(this, "Please Select Your Gender", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                int genser = 0;

                if (male.isSelected()) {
                    genser = 1;
                }
                if (female.isSelected()) {
                    genser = 2;
                }

                try {

                    connection_ol.iud("UPDATE `school_project(o/l)`.`admin` SET `fast_name`='" + fname + "' , `last_name`='" + lname + "',`password`='" + password + "',"
                            + "`user_type_user_type_id`='" + user_type_map.get(user_type) + "',`gender_gender_id`='" + genser + "' WHERE  `admin_id`='" + EID + "'");

                    clear();
                    loadEmployeeTable();

                    JOptionPane.showMessageDialog(this, "Update Success.", "Success", JOptionPane.OK_OPTION);

                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }

    }//GEN-LAST:event_buttonGradient2ActionPerformed

    private void buttonGradient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient3ActionPerformed

        if (employee_table.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please Select Employee to update or remove", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                
                if(status.equals("1")){
                    connection_ol.iud("UPDATE `admin` SET `status_status_id`='2' WHERE  `admin_id`='" + EID + "'");
                JOptionPane.showMessageDialog(this, "This Employee Deactivate.", "Success", JOptionPane.WARNING_MESSAGE);
                }else{
                    connection_ol.iud("UPDATE `admin` SET `status_status_id`='1' WHERE  `admin_id`='" + EID + "'");
                JOptionPane.showMessageDialog(this, "Now This Employee Activa.", "Success", JOptionPane.OK_OPTION);
                }
                
                clear();
                loadEmployeeTable();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_buttonGradient3ActionPerformed

    private void employee_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_tableMouseClicked
        if (evt.getClickCount() == 2) {

            buttonGradient3.setEnabled(true);
            buttonGradient2.setEnabled(true);
            buttonGradient1.setEnabled(false);

            email_field.setEditable(false);
            mobile_field.setEditable(false);

            int row = employee_table.getSelectedRow();

            EID = String.valueOf(employee_table.getValueAt(row, 0));

            try {

                ResultSet rs3 = connection_ol.search("SELECT * FROM `admin` WHERE `admin_id` = '" + String.valueOf(employee_table.getValueAt(row, 0)) + "'");

                if (rs3.next()) {
                    fname_field.setText(String.valueOf(employee_table.getValueAt(row, 1)));
                    lname_field.setText(String.valueOf(employee_table.getValueAt(row, 2)));
                    email_field.setText(String.valueOf(employee_table.getValueAt(row, 3)));
                    password_filed.setText(String.valueOf(employee_table.getValueAt(row, 4)));
                    mobile_field.setText(String.valueOf(employee_table.getValueAt(row, 5)));
                    String user_type = String.valueOf(employee_table.getValueAt(row, 6));
                    user_type_combo.setSelectedItem(user_type);

                    if (String.valueOf(employee_table.getValueAt(row, 7)).equals("Male")) {
                        male.setSelected(true);
                    } else if (String.valueOf(employee_table.getValueAt(row, 7)).equals("Female")) {
                        female.setSelected(true);
                    }
                    
                    if(String.valueOf(employee_table.getValueAt(row, 8)).equals("ACTIVE")){
                        buttonGradient3.setText("Deactive");
                        status = "1";
                    }else{
                        status = "2";
                        buttonGradient3.setText("Active");
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_employee_tableMouseClicked

    private void search_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_fieldKeyPressed
       
        String search = search_field.getText();
        
        try {
            ResultSet rs = connection_ol.search("SELECT * FROM `admin` INNER JOIN `user_type` ON `admin`.`user_type_user_type_id`=`user_type`.`user_type_id` "
                    + "INNER JOIN `gender` ON `admin`.`gender_gender_id`=`gender`.`gender_id` "
                    + "INNER JOIN `status` ON `admin`.`status_status_id`=`status`.`status_id` "
                    + "WHERE `fast_name`  LIKE '" + search + "%' OR `last_name` LIKE '" + search + "%'");

            DefaultTableModel model = (DefaultTableModel) employee_table.getModel();
            model.setRowCount(0);
            
            while (rs.next()) {
                Vector employeeVector = new Vector();
                employeeVector.add(rs.getString("admin_id"));
                employeeVector.add(rs.getString("fast_name"));
                employeeVector.add(rs.getString("last_name"));
                employeeVector.add(rs.getString("email"));
                employeeVector.add(rs.getString("password"));
                employeeVector.add(rs.getString("mobile"));
                employeeVector.add(rs.getString("user_type.type"));
                employeeVector.add(rs.getString("gender.name"));
                employeeVector.add(rs.getString("status.status"));

                model.addRow(employeeVector);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_search_fieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SMMV.Component.Background background1;
    private SMMV.Component.Background background2;
    private SMMV.Component.Background background3;
    private SMMV.Component.Background background4;
    private SMMV.Component.Background background5;
    private SMMV.Component.ButtonGradient buttonGradient1;
    private SMMV.Component.ButtonGradient buttonGradient2;
    private SMMV.Component.ButtonGradient buttonGradient3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField email_field;
    private javax.swing.JTable employee_table;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname_field;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile_field;
    private javax.swing.JPasswordField password_filed;
    private SMMV.Component.Rount_textfieald search_field;
    private javax.swing.JComboBox<String> user_type_combo;
    // End of variables declaration//GEN-END:variables
}
