/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SMMV.OL.form;

import SMMV.Connection.connection_ol;
import SMMV.OL.model.User_id_Genarator;
import SMMV.Validation.Validation;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Teacher extends javax.swing.JPanel {
    
    String TID = "";

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        setOpaque(false);
        init();
    }

    private void init() {

        buttonGradient1.setEnabled(true);
        buttonGradient2.setEnabled(false);
        buttonGradient3.setEnabled(false);

        email_field.setEditable(true);
        mobile_field.setEditable(true);

        fname_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter First Name");
        lname_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Last Name");
        email_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Email Address");
        mobile_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Mobile");
        line1_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Address Line 1");
        line2_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Address Line 2");
        search_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Search Employee");
        JTableHeader tableHeader = teacher_table.getTableHeader();
        tableHeader.setBackground(new Color(0, 0, 255));
        tableHeader.setForeground(Color.WHITE);

        try {

            ResultSet rs = connection_ol.search("SELECT * FROM `teacher` INNER JOIN `status` ON `teacher`.`status_status_id` = `status`.`status_id` "
                    + "INNER JOIN `gender` ON `teacher`.`gender_gender_id` = `gender`.`gender_id`");

            DefaultTableModel model = (DefaultTableModel) teacher_table.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector supplierVector = new Vector();
                supplierVector.add(rs.getString("teacher_id"));
                supplierVector.add(rs.getString("first_name"));
                supplierVector.add(rs.getString("last_name"));
                supplierVector.add(rs.getString("email"));
                supplierVector.add(rs.getString("mobile"));
                supplierVector.add(rs.getString("gender.name"));
                supplierVector.add(rs.getString("status.status"));

                model.addRow(supplierVector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void clear() {
        fname_field.setText("");
        lname_field.setText("");
        email_field.setText("");
        mobile_field.setText("");
        line1_field.setText("");
        line2_field.setText("");
        buttonGroup1.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        background1 = new SMMV.Component.Background();
        background2 = new SMMV.Component.Background();
        background4 = new SMMV.Component.Background();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mobile_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        fname_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lname_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        line1_field = new javax.swing.JTextField();
        line2_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        buttonGradient1 = new SMMV.Component.ButtonGradient();
        buttonGradient2 = new SMMV.Component.ButtonGradient();
        buttonGradient3 = new SMMV.Component.ButtonGradient();
        background3 = new SMMV.Component.Background();
        background5 = new SMMV.Component.Background();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        search_field = new SMMV.Component.Rount_textfieald();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacher_table = new javax.swing.JTable();

        background1.setBackground(new java.awt.Color(0, 0, 0));

        background4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SMMV/OL/img/teacher.png"))); // NOI18N

        javax.swing.GroupLayout background4Layout = new javax.swing.GroupLayout(background4);
        background4.setLayout(background4Layout);
        background4Layout.setHorizontalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background4Layout.setVerticalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Manage Teacher");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        email_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile");

        mobile_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        male.setText("Male");

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        female.setText("Female");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First Name");

        fname_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Name");

        lname_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address Line 1");

        line1_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        line2_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address Line 2");

        buttonGradient1.setText("Add New Teacher");
        buttonGradient1.setColor1(new java.awt.Color(0, 0, 153));
        buttonGradient1.setColor2(new java.awt.Color(139, 139, 252));
        buttonGradient1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1ActionPerformed(evt);
            }
        });

        buttonGradient2.setText("Update");
        buttonGradient2.setColor1(new java.awt.Color(0, 0, 153));
        buttonGradient2.setColor2(new java.awt.Color(139, 139, 252));
        buttonGradient2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGradient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient2ActionPerformed(evt);
            }
        });

        buttonGradient3.setText("Deactive");
        buttonGradient3.setColor1(new java.awt.Color(0, 0, 153));
        buttonGradient3.setColor2(new java.awt.Color(139, 139, 252));
        buttonGradient3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGradient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(background2Layout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(43, 43, 43)
                        .addComponent(female))
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(line2_field)
                    .addComponent(line1_field)
                    .addComponent(mobile_field)
                    .addComponent(email_field)
                    .addComponent(lname_field)
                    .addComponent(fname_field)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                        .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(background2Layout.createSequentialGroup()
                        .addComponent(buttonGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(fname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(lname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(mobile_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addComponent(line1_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(5, 5, 5)
                .addComponent(line2_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        background5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SMMV/OL/img/search.png"))); // NOI18N

        javax.swing.GroupLayout background5Layout = new javax.swing.GroupLayout(background5);
        background5.setLayout(background5Layout);
        background5Layout.setHorizontalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background5Layout.setVerticalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Search Teacher");

        search_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        teacher_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        teacher_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Mobile", "Gender", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teacher_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teacher_tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(teacher_table);

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(search_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background3Layout.createSequentialGroup()
                        .addComponent(background5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 386, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(background5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1ActionPerformed
        if (fname_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Fast Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (lname_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (email_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Email Address", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!email_field.getText().matches(Validation.EMAIL_VALIDATION.validate())) {
            JOptionPane.showMessageDialog(this, "Your Email Address Is Invalide", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (mobile_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Mobile Number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!mobile_field.getText().matches(Validation.MOBILE_NUMBER_VALIDATION.validate())) {
            JOptionPane.showMessageDialog(this, "Your Mobile Number Is Invalide", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (line1_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Address Line 1", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (line2_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Address Line 2", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!male.isSelected() && !female.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please Select Your Gender", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            int genser = 0;

            if (male.isSelected()) {
                genser = 1;
            }
            if (female.isSelected()) {
                genser = 2;
            }

            try {

                connection_ol.iud("INSERT INTO `teacher` (`teacher_id`,`first_name`,`last_name`,`email`,`mobile`,`line_1`,`line_2`,`gender_gender_id`,`status_status_id`) "
                        + "VALUES ('" + User_id_Genarator.User_id_Genarator() + "','" + fname_field.getText() + "','" + lname_field.getText() + "','" + email_field.getText() + "',"
                        + "'" + mobile_field.getText() + "','" + line1_field.getText() + "','" + line2_field.getText() + "','" + genser + "','1')");

                System.out.println("Success");
                clear();

            } catch (Exception e) {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_buttonGradient1ActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void teacher_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher_tableMousePressed
        if (evt.getClickCount() == 2) {

            buttonGradient3.setEnabled(true);
            buttonGradient2.setEnabled(true);
            buttonGradient1.setEnabled(false);

            email_field.setEditable(false);
            mobile_field.setEditable(false);

            int row = teacher_table.getSelectedRow();
            
            TID = String.valueOf(teacher_table.getValueAt(row, 0));

            try {

                ResultSet rs3 = connection_ol.search("SELECT * FROM `teacher` WHERE `teacher_id` = '" + String.valueOf(teacher_table.getValueAt(row, 0)) + "'");

                if (rs3.next()) {
                    fname_field.setText(String.valueOf(teacher_table.getValueAt(row, 1)));
                    lname_field.setText(String.valueOf(teacher_table.getValueAt(row, 2)));
                    email_field.setText(String.valueOf(teacher_table.getValueAt(row, 3)));
                    mobile_field.setText(String.valueOf(teacher_table.getValueAt(row, 4)));

                    line1_field.setText(rs3.getString("line_1"));
                    line2_field.setText(rs3.getString("line_2"));

                    if (String.valueOf(teacher_table.getValueAt(row, 5)).equals("MALE")) {
                        male.setSelected(true);
                    } else if (String.valueOf(teacher_table.getValueAt(row, 5)).equals("FEMALE")) {
                        female.setSelected(true);
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_teacher_tableMousePressed

    private void buttonGradient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient3ActionPerformed

        try {
            connection_ol.iud("UPDATE `teacher` SET `status_status_id`='2' WHERE  `teacher_id`='" + TID + "'");
            clear();
            init();
            JOptionPane.showMessageDialog(this, "This Teacher Removed.", "Success", JOptionPane.OK_OPTION);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_buttonGradient3ActionPerformed

    private void buttonGradient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient2ActionPerformed
        String fname = fname_field.getText();
        String lname = lname_field.getText();
        String line1 = line1_field.getText();
        String line2 = line2_field.getText();

        if (fname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Fast Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (lname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (line1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Address Line 1", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (line2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Address Line 2", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {

                connection_ol.iud("UPDATE `school_project(o/l)`.`teacher` SET `first_name`='"+fname+"' , `last_name`='"+lname+"' , `line_1`='"+line1+"' , `line_2`='"+line2+"' "
                        + "WHERE  `teacher_id`='"+TID+"'");

                clear();
                init();
                
                JOptionPane.showMessageDialog(this, "Update Success.", "Success", JOptionPane.OK_OPTION);

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_buttonGradient2ActionPerformed

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SMMV.Component.Background background1;
    private SMMV.Component.Background background2;
    private SMMV.Component.Background background3;
    private SMMV.Component.Background background4;
    private SMMV.Component.Background background5;
    private SMMV.Component.ButtonGradient buttonGradient1;
    private SMMV.Component.ButtonGradient buttonGradient2;
    private SMMV.Component.ButtonGradient buttonGradient3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField email_field;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField line1_field;
    private javax.swing.JTextField line2_field;
    private javax.swing.JTextField lname_field;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile_field;
    private SMMV.Component.Rount_textfieald search_field;
    private javax.swing.JTable teacher_table;
    // End of variables declaration//GEN-END:variables
}
