/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SMMV.Main;

import SMMV.Connection.connection_ol;
import SMMV.OL.model.Login_user_details;
import SMMV.OL.model.Status;
import SMMV.OL.model.User_type;
import SMMV.Validation.Validation;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.demo.FlatLafDemo;
import com.formdev.flatlaf.intellijthemes.FlatNordIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatNightOwlIJTheme;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import raven.toast.Notifications;

/**
 *
 * @author user
 */
public class Sign_In extends javax.swing.JFrame {

    public static Login_user_details details = new Login_user_details();
    /**
     * Creates new form Sign_In
     */
    public Sign_In() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        init();
        loaduser_type();
    }

    private void init() {
        jLabel2.setText("<html>"
                + "Subharathi Mahamathya Maha Vidyalaya's software can be logged in only by authorized persons. Email, password can be entered only."
                + "</html>");

        ImageIcon icon = new ImageIcon(getClass().getResource("/SMMV/OL/img/SMMV.png"));
        this.setIconImage(icon.getImage());

        email_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Your Email Address");
        password_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter Your Password");

        Notifications.getInstance().setJFrame(this);
    }

    private void loaduser_type() {

        try {

            Vector<String> vector = new Vector<>();
            vector.add("SELECT USER TYPE");

            ResultSet user_type = connection_ol.search("SELECT * FROM `user_type`");

            while (user_type.next()) {
                vector.add(user_type.getString("type"));
            }

            user_type_combo.setModel(new DefaultComboBoxModel<>(vector));
        } catch (SQLException e) {

            throw new RuntimeException(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanelElement1 = new SMMV.Component.roundPanelElement();
        roundPanelElement2 = new SMMV.Component.roundPanelElement();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roundPanelElement3 = new SMMV.Component.roundPanelElement();
        jLabel4 = new javax.swing.JLabel();
        buttonGradient1 = new SMMV.Component.ButtonGradient();
        buttonGradient2 = new SMMV.Component.ButtonGradient();
        jSeparator1 = new javax.swing.JSeparator();
        student_type_combo = new javax.swing.JComboBox<>();
        email_field = new SMMV.Component.Rount_textfieald();
        password_field = new SMMV.Component.Rount_textfieald_password();
        user_type_combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        roundPanelElement1.setBackground(new java.awt.Color(220, 220, 221));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SMMV/OL/img/SMMV.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 0, 135));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SUBHARATHI MAHAMATHYA MAHA VIDYALAYA");

        javax.swing.GroupLayout roundPanelElement2Layout = new javax.swing.GroupLayout(roundPanelElement2);
        roundPanelElement2.setLayout(roundPanelElement2Layout);
        roundPanelElement2Layout.setHorizontalGroup(
            roundPanelElement2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelElement2Layout.createSequentialGroup()
                .addGroup(roundPanelElement2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanelElement2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(roundPanelElement2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanelElement2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        roundPanelElement2Layout.setVerticalGroup(
            roundPanelElement2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelElement2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 204));
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login to your account");

        buttonGradient1.setText("Login now");
        buttonGradient1.setColor1(new java.awt.Color(255, 0, 0));
        buttonGradient1.setColor2(new java.awt.Color(246, 96, 92));
        buttonGradient1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        buttonGradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1ActionPerformed(evt);
            }
        });

        buttonGradient2.setText("Exit application");
        buttonGradient2.setColor1(new java.awt.Color(0, 0, 0));
        buttonGradient2.setColor2(new java.awt.Color(89, 88, 88));
        buttonGradient2.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        buttonGradient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient2ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        student_type_combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        student_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student Type", "Primary Student ", "O/L Student", "A/L Student" }));

        email_field.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        password_field.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        user_type_combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout roundPanelElement3Layout = new javax.swing.GroupLayout(roundPanelElement3);
        roundPanelElement3.setLayout(roundPanelElement3Layout);
        roundPanelElement3Layout.setHorizontalGroup(
            roundPanelElement3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelElement3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(roundPanelElement3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student_type_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_type_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGradient2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        roundPanelElement3Layout.setVerticalGroup(
            roundPanelElement3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelElement3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(student_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(user_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout roundPanelElement1Layout = new javax.swing.GroupLayout(roundPanelElement1);
        roundPanelElement1.setLayout(roundPanelElement1Layout);
        roundPanelElement1Layout.setHorizontalGroup(
            roundPanelElement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelElement1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(roundPanelElement2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(roundPanelElement3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        roundPanelElement1Layout.setVerticalGroup(
            roundPanelElement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanelElement1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(roundPanelElement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundPanelElement3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundPanelElement2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanelElement1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanelElement1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGradient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonGradient2ActionPerformed

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1ActionPerformed

        String email = email_field.getText();
        String password = String.valueOf(password_field.getPassword());
        String student_type = String.valueOf(student_type_combo.getSelectedItem());
        String user_type = String.valueOf(user_type_combo.getSelectedItem());

        if (email.isEmpty()) {
//            Notifications.getInstance().show(Notifications.Type.WARNING,Notifications.Location.TOP_LEFT, "Please Enter Your Email Address");
            JOptionPane.showMessageDialog(this, "Please Enter Your Email Address", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!email.matches(Validation.EMAIL_VALIDATION.validate())) {
            JOptionPane.showMessageDialog(this, "Your Email Address Is Invalide", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Password", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!password.matches(Validation.PASSWORD_VALIDATION.validate())) {
            JOptionPane.showMessageDialog(this, "Invalid Your Password", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (student_type.equals("Select Student Type")) {
            JOptionPane.showMessageDialog(this, "Please Select Student Type", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (user_type.equals("SELECT USER TYPE")) {
            JOptionPane.showMessageDialog(this, "Please Select User Type", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {

                ResultSet UserLoging = connection_ol.search("SELECT * FROM `admin`"
                        + " INNER JOIN `user_type` ON `admin`.`user_type_user_type_id` = `user_type`.`user_type_id` "
                        + "INNER JOIN `status` ON `admin`.`status_status_id` = `status`.`status_id` "
                        + "INNER JOIN `gender` ON `admin`.`gender_gender_id` = `gender`.`gender_id` "
                        + "WHERE `email`='" + email + "' AND `password`='" + password + "'");

                if (UserLoging.next()) {

                    String status = UserLoging.getString("status.status");
                    String usertype = UserLoging.getString("user_type.type");

                    if (status.equals(Status.ACTIVE.name())) {
                        if (usertype.equals(User_type.PRINCIPALE.name())) {

                            String user_name = UserLoging.getString("user_name");
                            String user_email = UserLoging.getString("email");
                            String mobile = UserLoging.getString("mobile");
                            String gender = UserLoging.getString("gender.name");
                            String user_id = UserLoging.getString("admin_id");
                            
                            Sign_In.details.setEmail(user_email);
                            Sign_In.details.setUser_mobile(mobile);
                            Sign_In.details.setUsername(user_name);
                            Sign_In.details.setGender(gender);
                            Sign_In.details.setUser_type(usertype);
                            Sign_In.details.setUser_id(user_id);

                        } else if (usertype.equals(User_type.WISE_PRINCIPALE.name())) {


                            String user_name = UserLoging.getString("user_name");
                            String user_email = UserLoging.getString("email");
                            String mobile = UserLoging.getString("mobile");
                            String gender = UserLoging.getString("gender.name");
                            String user_id = UserLoging.getString("admin_id");
                            
                            Sign_In.details.setEmail(user_email);
                            Sign_In.details.setUser_mobile(mobile);
                            Sign_In.details.setUsername(user_name);
                            Sign_In.details.setGender(gender);
                            Sign_In.details.setUser_type(usertype);
                            Sign_In.details.setUser_id(user_id);

                        } else if (usertype.equals(User_type.IT_SECTION.name())) {

                            String user_name = UserLoging.getString("user_name");
                            String user_email = UserLoging.getString("email");
                            String mobile = UserLoging.getString("mobile");
                            String gender = UserLoging.getString("gender.name");
                            String user_id = UserLoging.getString("admin_id");
                            
                            Sign_In.details.setEmail(user_email);
                            Sign_In.details.setUser_mobile(mobile);
                            Sign_In.details.setUsername(user_name);
                            Sign_In.details.setGender(gender);
                            Sign_In.details.setUser_type(usertype);
                            Sign_In.details.setUser_id(user_id);
                            
                            

                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "User session is not activated.Please cantact administrator", "Warning", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Your Login Details", "Warning", JOptionPane.WARNING_MESSAGE);
                }

            } catch (SQLException e) {
                throw new RuntimeException(e);
            }

        }
    }//GEN-LAST:event_buttonGradient1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        FlatMacLightLaf.setup();
//        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SMMV.Component.ButtonGradient buttonGradient1;
    private SMMV.Component.ButtonGradient buttonGradient2;
    private SMMV.Component.Rount_textfieald email_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private SMMV.Component.Rount_textfieald_password password_field;
    private SMMV.Component.roundPanelElement roundPanelElement1;
    private SMMV.Component.roundPanelElement roundPanelElement2;
    private SMMV.Component.roundPanelElement roundPanelElement3;
    private javax.swing.JComboBox<String> student_type_combo;
    private javax.swing.JComboBox<String> user_type_combo;
    // End of variables declaration//GEN-END:variables
}
